dist: trusty
sudo: false

language: node_js
node_js:
  - '9'

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng test --watch=false --browsers=ChromeHeadless
