dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run ci-test
